spring:
  application:
    name: eureka-turbine
server:
  port: 8088
management:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://replica1:8081/eureka,http://replica2:8082/eureka,http://replica3:8083/eureka
turbine:
  app-config: hystrix-dashboard
  cluster-name-expression: new String("default")
  combine-host-port: true