server:
  port: 8084
spring:
  application:
    name: eureka-producer
eureka:
  client:
    service-url:
      defaultZone: http://replica1:8081/eureka,http://replica2:8082/eureka,http://replica3:8083/eureka
