server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paascloud_zipkin?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  application:
    name: eureka-producer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/
