spring:
  application:
    name: eureka-gateway
server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
zuul:
  routes:
    api-fegin:
      id: /api-fegin/**
      serviceId: eureka-feign
    api-producer:
      id: /api-producer/**
      serviceId: eureka-producer